### ISSUE TITLE
I found that the index does not work in this version

### ISSUE THREAD

**Issue by sxdxyxy** [linuxmint/xreader#29] opened 2016-07-23 07:48 UTC
When I navigate the file content using a index, the content does not move to the position what I  expect, so I  do not know any others have the same issue as me?

**Comment by Piiit** [comment] 2016-08-22 08:03
This sometimes depend on your PDF, is the index working with other PDF readers? Could you please upload your test file?

**Comment by Piiit** [comment] 2016-11-05 11:39
@sxdxyxy Hi, some news on this? Could you provide an example document? Is it PDF or another file format?

**Comment by Piiit** [comment] 2017-03-22 09:57
Duplicate of #90

**Closed** 2017-03-22 10:03 UTC
