### ISSUE TITLE
Xreader close when PDF change

### ISSUE THREAD

**Issue by hakostra** [linuxmint/xreader#33] opened 2016-08-18 11:01 UTC
With Evince, I can open a PDF, and each time that PDF changes, Evince discovers this and update the document. This is very handy when editing and recompiling latex documents, PDF figures  with scripts etc. I can just keep Evince open and it will always show the most recent version of a document during successive recompilations.

If a document open in Xreader change on disk, Xreader close, and I have to manually open that document again, which is quite annoying.

Is there any chance of having Xreader behave like Evince in this respect?

**Comment by Piiit** [comment] 2016-08-22 08:01
Hi,
I think this is a duplicate of #25 which has already been fixed with #28. 
Could you please check if this patch also fixes your issue?

**Comment by reaganf2** [comment] 2016-09-18 02:00
Hi

I'm running xreader 1.0.8 on LM18, and have found that although xreader does not close automatically when a PDF is recompiled using pdflated, the updated PDF is not automatically loaded. Evince used to autoreload the updated PDF which used to be EXTREMELY useful when writing documents in LaTeX. Would be great if this feature is implemented.

I'm not sure if this has anything to do with the fact that even Nemo doesn't automatically refresh the current folder when its contents are changed externally, as it used to in LM17.3.

This may also have to do with the Crash on Reload (#44) issue.

**Comment by Piiit** [comment] 2016-09-18 14:39
@reaganf2 The bug fix has been introduced later, therefore you could try to beta test the new version.
Steps to do that with a terminal are as follows:
```
mkdir xreader-beta
cd xreader-beta
wget https://github.com/linuxmint/xreader/archive/master.zip
unzip master.zip
cd xreader-master
dpkg-buildpackage
```

This takes some minutes, just wait. At the end it may show some errors about keys and stuff, but don't worry... Now you can go back to xreader-beta folder and install the debian packages.

```
sudo dpkg -i ../*.deb
```

If you start xreader now, it comes up with the new version. However, this version is beta and may not be as stable as v1.0.8. 

To uninstall it, and the default LM18 version again, just issue: `sudo apt install xreader`.

Cheers!

**Comment by reaganf2** [comment] 2016-09-19 01:42
:-) Thank you so much. That solved it.

**Comment by Piiit** [comment] 2016-09-19 05:34
You're welcome 😁

**Comment by Piiit** [comment] 2016-09-19 12:31
@clefebvre @mtwebster This issue can be closed.

**Closed** 2016-09-23 14:46 UTC

**Comment by jeisner** [comment] 2017-01-28 04:57
Shouldn't this bug be gone now?  But I'm getting it with xreader 1.2.2, having installed LM18.1 "Serena" a week or two ago.  

The discussion above suggests that it should have been fixed in the next version after xreader 1.0.8.  Please advise.

**Comment by reaganch** [comment] 2018-07-17 04:12
Just wanted to note that this bug just reappeared in Xreader 1.8.4 after upgrading to LM19.

**Comment by reaganch** [comment] 2020-08-05 02:18
This bug has reappeared in Xreader 2.6.4 after upgrading to LM20. The updated PDF file is not automatically loaded by Xreader after compiling using pdflatex.

**Comment by jeisner** [comment] 2020-08-05 03:29
> This bug has reappeared in Xreader 2.6.4 after upgrading to LM20. The updated PDF file is not automatically loaded by Xreader after compiling using pdflatex.

Hmm, I just did a fresh install of LM20 a couple of weeks ago, and auto-reload in Xreader 2.6.4 works fine for me.

**Comment by reaganch** [comment] 2020-08-05 03:35
Mine was a fresh installation of LM20 too. Any suggestions how I might go about trying to find the cause of this? The absence of the auto-reload feature makes using LaTeX pretty inconvenient indeed.
