### ISSUE TITLE
Having selected text leads to high cpu load.

### ISSUE THREAD

**Issue by borko1945** [linuxmint/xreader#70] opened 2016-11-12 15:57 UTC
When I have something(text) selected the cpu load gets 100%.
Scrolling and hiding the selection does not change the situation.
When focus is changed to another window cpu load goes to 0%.
When focusing again on Xreader(which has text selected) cpu load rises again.
Clearing the selection makes cpu load lower to 0%.

Occurs on Xreader 1.0.8
Host OS: Windows 7 running Vmware Workstation 12 Player
Guest OS: Linux Mint Sarah 18 64-bit Cinnamon edition. 

![screenshot from 2016-11-12 17-55-59](https://cloud.githubusercontent.com/assets/5305158/20239112/84fd8088-a901-11e6-9f58-1b66ced47194.png)

**Comment by Piiit** [comment] 2016-11-12 17:22
@borko1945 Please post the actual memory stats of xreader, the screenshot does not show xreader related stats as I can see.... Does it happen only with this PDF or with all? Do you have similar issues when selecting text in another app?

**Comment by borko1945** [comment] 2016-11-13 11:36
@Piiit. It is reproducible with the other pdf book I have too. I installed Evince viewer, which does not have such issue. 
![screenshot from 2016-11-13 13-36-05](https://cloud.githubusercontent.com/assets/5305158/20245267/37f6402c-a9a6-11e6-8d1b-2aef38e0a78d.png)

**Comment by Piiit** [comment] 2016-11-13 11:39
@borko1945 Thanks for reporting, why have you closed this issue already?

**Comment by borko1945** [comment] 2016-11-13 11:41
Sorry, not used with GitHub.
How can I reopen it ?

**Comment by outhud** [comment] 2017-01-09 17:57
I'm also seeing this bug. Linux Mint 18.1, Xreader 1.2.2.

If I have text highlighted, xreader cpu usage shoots up to 50-60% when the xreader window is active.

When i unselect text, or change the active window, the usage goes back down to 0-1%.

**Comment by Piiit** [comment] 2017-01-12 06:21
This bug happens now also on my machine. LM18.1 with xreader 1.2.1...

**Comment by Timmy93** [comment] 2017-02-05 14:03
I can confirm the bug.
LM18.1 - Cinnamon
xreader 1.2.2
Insalled in a real PC as unique OS, no VM.

Tested the same pdf on evince and I had no problem. (I imagine that xreader is a fork of evince)

**Comment by carsonip** [comment] 2017-02-27 22:45
I can confirm the bug too.
LM18.1 Cinnamon, xreader 1.2.2

xreader uses <10% cpu usually. With highlighted text, it uses >60% cpu and there is a significant increase in CPU usage of Xorg too.

**Comment by jeisner** [comment] 2017-03-16 06:05
Also confirming, this time with Linux Mint 18.1 - MATE edition.   
xreader 1.2.2, as for others.
And yes, top shows that xreader and Xorg both shoot up.

I'd noticed that my system seemed to slow to a crawl in this way. So I was killing xreader.  Thanks to this issue for pointing out that it's enough to deselect text.

**Comment by Piiit** [comment] 2017-03-17 08:45
Tested it with Atril 1.18.0... same issue.

**Comment by OmarTrigui** [comment] 2017-04-10 14:17
Confirmed. 
High cpu usage without any interaction or content selection of any opened PDF file.
LM 18.1 Cinnamon, xreader 1.2.2

**Comment by scytho** [comment] 2017-05-04 10:29
I’m encountering this issue too, with Xreader 1.2.2 on Mint 18.1 x64. It’s not only the CPU load, most of the time selecting text doesn’t work at all. If I select text slowly and carefully, Xreader selects two or three letters, not more. CPU load goes up anyway, even when selection doesn’t work at all. This issue is related to that one: #95

Example for a PDF: http://mirrors.ctan.org/macros/latex/contrib/koma-script/doc/scrguien.pdf

**Comment by Piiit** [comment] 2017-05-04 11:30
@scytho I cannot reproduce the text selection issues you describe with your example document. I can select the text without any problems. Nevertheless, the cpu load is too high, but that problem is not related I think. Does this only happen in XFCE or also mate or cinnamon?

**Comment by scytho** [comment] 2017-05-04 12:36
I’m using only Mate at the moment (Mate 1.16.1).

**Closed** 2017-06-19 10:48 UTC
Labels: BUG REPRODUCED

**Comment by jerkey** [comment] 2023-07-13 21:35
I'm still experiencing this "Having selected text leads to high cpu load", xreader was eating an entire CPU core.
xreader 3.2.2
Linux eg 5.4.0-137-generic #154-Ubuntu SMP Thu Jan 5 17:03:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
Linux Mint 20.3
