### ISSUE TITLE
Text highlight works bad.

### ISSUE THREAD

**Issue by javadmokhtari** [linuxmint/xreader#341] opened 2019-11-25 07:26 UTC
```
 * Xreader version 2.0.2
 * Distribution - Linux Mint 19.1 Cinnamon 4.0.10
```

**Issue**
When I highlight (select) a text, the text becomes unreadable. like you see in picture:

![Screenshot from 2019-11-25 10-45-10](https://user-images.githubusercontent.com/28118126/69520228-516c6200-0f71-11ea-80f7-1d27a5b98987.png)

**Steps to reproduce**

1. Download PDF: [Link](https://javad.dev/concepts.pdf)
2. Open it.
3. Select a part of text.

**Expected behaviour**

![Screenshot from 2019-11-25 10-45-17](https://user-images.githubusercontent.com/28118126/69520208-444f7300-0f71-11ea-888d-73140d8a84d1.png)

**Comment by icarter09** [comment] 2019-12-19 03:49
@javadmokhtari where exactly did you get that PDF? I've tried duplicating this issue with several other PDFs, but had no luck. But I am able to reproduce the issue with that PDF.

**Comment by javadmokhtari** [comment] 2019-12-21 09:27
> @javadmokhtari where did you get that PDF? I've tried duplicating this issue with several other PDFs, but had no luck. But I am able to reproduce the issue with that PDF.

@icarter09 The main source is [THIS](https://homepages.dcc.ufmg.br/~camarao/lp/concepts.pdf) url. When I open it with Google Chrome, syntax highlighting works fine. So It seems that problem relates to xreader rather than PDF file.

**Comment by icarter09** [comment] 2019-12-21 15:57
@javadmokhtari I think you are correct. While I'm not able to duplicate it with any other PDF in xreader, the issue doesn't appear in Chrome. Looking at the syntax highlighting, it appears like the words are backwards and layered on top of one another.

**Comment by javadmokhtari** [comment] 2019-12-22 08:36
@icarter09 I have seen this bug with some other files too. I am going to share them ASAP. Anyway thanks for your attention and I hope you can fix it. Good Luck.

**Comment by icarter09** [comment] 2020-04-25 17:59
@javadmokhtari sorry for the late reply. I'm going to close this ticket since it's an issue with Poppler and not Xreader. I've posted comments on #381 for what I was able to find.

**Closed by icarter09** 2020-04-25 17:59 UTC
Labels: BUG, BUG REPRODUCED
