### ISSUE TITLE
Unimplemented annotation: POPPLER_ANNOT_STAMP

### ISSUE THREAD

**Issue by eku** [linuxmint/xreader#230] opened 2018-05-31 12:15 UTC
```
 * Xreader version (xreader --version)
   xreader-1.8.1-1.fc28
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
   Fedora 28
```

**Issue**

** (xreader:5318): WARNING **: 18:34:28.012: Unimplemented annotation: POPPLER_ANNOT_STAMP, please post a bug report on Xreader bug tracker (https://github.com/linuxmint/xreader/issues) with a testcase.

**Steps to reproduce**

xreader instruction_booklet.pdf

**Expected behaviour**

No warning at all.

**Other information**
Can't attach the PDF file.

**Comment by Piiit** [comment] 2018-11-03 09:39
Duplicate of #66

**Closed** 2019-06-25 10:45 UTC
