### ISSUE TITLE
Xreader closes/crashes when building the PDF from latex while open

### ISSUE THREAD

**Issue by elDan101** [linuxmint/xreader#62] opened 2016-10-22 09:53 UTC
Software:
TeXstudio 2.10.8. 
Xreader 1.0.8

Unfortunately, it only sometimes happens and is not deterministic: 

When I have a PDF opened in Xreader and do some changes in Latex and build the PDF again, the PDF closes/crashes. When it closes it is exactly at building in TeXstudio.

**Comment by Piiit** [comment] 2016-10-28 13:41
@elDan101 Hi, this seems to be a duplicate of an already solved bug (see #33 and #44). Could you try to beta test the new version? See https://github.com/linuxmint/xreader/issues/33#issuecomment-247851424 for further details.

**Closed** 2016-11-02 18:41 UTC

**Comment by elDan101** [comment] 2016-11-02 18:44
I havn't tested it because I get this error when executing dpkg-buildpackage:

Unmet build dependencies: gobject-introspection libnemo-extension-dev libdjvulibre-dev libgail-3-dev libgirepository1.0-dev libgtk-3-dev libgxps-dev libkpathsea-dev libpoppler-glib-dev libsecret-1-dev libspectre-dev libwebkit2gtk-3.0-dev (>= 2.4.3) | libwebkit2gtk-4.0-dev (>= 2.4.3) mate-common (>= 1.12) xsltproc yelp-tools

I couldn't fix that immediately, so I will keep this in mind. If I still observe this after an update I will make another issue.

**Comment by JosephMcc** [comment] 2016-11-02 18:50
You just need to `apt install` each of those missing dependencies.

**Comment by elDan101** [comment] 2016-11-02 18:53
I tried this, but the first package was not available already:

sudo apt-get install gobject-introspection
[...]
Package gobject-introspection is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source.

**Comment by elDan101** [comment] 2016-11-02 18:54
Ahh I see it is "apt install" only. Okay will do this now.

**Comment by JosephMcc** [comment] 2016-11-02 18:57
The effect is the same between the two commands. What do you get when doing `apt search gobject-introspection` ?

On Mint you might need to go open Software sources and check "Enable source code repositories" and then click the "Update the cache" button and try again.

**Comment by elDan101** [comment] 2016-11-02 19:03
> The effect is the same between the two commands. 

Hm... with this command (sudo apt install gobject-introspection) it installed without errors and also before I enabled "source code repositories".  

 apt search gobject-introspection gives (now after installation):

> i   gobject-introspection           - Generate interface introspection data for 
> p   gobject-introspection:i386      - Generate interface introspection data for 
> p   ruby-gobject-introspection      - GObject Introspection bindings for the Rub
> p   ruby-gobject-introspection:i386 - GObject Introspection bindings for the Rub
> p   ruby-gobject-introspection-dbg  - GObject Introspection bindings for the Rub
> p   ruby-gobject-introspection-dbg: - GObject Introspection bindings for the Rub

**Comment by JosephMcc** [comment] 2016-11-02 19:09
Ok, well you just need to install the other dependencies and then it should build.

**Comment by elDan101** [comment] 2016-11-02 19:21
I just did this and also build a latex file and try to crash it.
After now ~15 changes+builds it didn't crash. Xreader displays the changes after build correctly.  Normally, with the "old version", it takes 3-5 builds to crash -- so it seems it is fixed in the new version and this issue was a duplicate.

**Comment by Piiit** [comment] 2016-11-03 07:36
@elDan101 Hi, I am currently writing a new README that explains all these steps you did. Could you please post which packages you installed with `apt install`? That would help me to better describe beta testing...
Which kernel, distribution, DE (i.e., Cinnamon, Mate, ...) do you use?

**Comment by elDan101** [comment] 2016-11-03 07:54
Kernel = 4.4.0-45-generic
Distribution = Linux Mint 18
DE = Cinnamon v.  3.0.7

I installed all the packages that were stated as "missing dependencies" - when I had the choice I used the package with the higher version number:
gobject-introspection 
libnemo-extension-dev 
libdjvulibre-dev 
libgail-3-dev 
libgirepository1.0-dev 
libgtk-3-dev 
libgxps-dev 
libkpathsea-dev 
libpoppler-glib-dev 
libsecret-1-dev 
libspectre-dev 
libwebkit2gtk-3.0-dev
mate-common 
xsltproc 
yelp-tools
