### ISSUE TITLE
Cyrillic entered in PDF forms is not shown.

### ISSUE THREAD

**Issue by sergeypugachov** [linuxmint/xreader#208] opened 2018-02-10 07:23 UTC
```
 * Xreader version 1.6.1
 * Distribution - (Mint 18.3 Cinnamon)
```
When trying to fit cyrillic symbols in forms, it's not showing up. English symbols and numbers are ok. This issue starts from Mint 18.1 at least.

**Steps to reproduce**

1. Download test pdf (it's a bank anket).
https://1drv.ms/b/s!AuiHHJmnFFVK_VO9XrajAe6ANHs5
2. Fill any field with latin  - after complete, it will bi splited one symbol per cell
3. Now, fill with cyrillic - nothing happens.
4. If again focus at field, you can see data which you enter. But it's not display if focus lost, and not splitted in cellss.

I try different PDF-ankets from 3 independet sources (bank, goverment, another bank) - it's all the same behavior.

If open, fill, and save it in Acrobat Reader under Windows, it will be Reopened in Xreader, but if try to edit, issue reproduced (form with data example: https://1drv.ms/b/s!AuiHHJmnFFVK_VL-Y2I99f8jC8D_).

**Expected behaviour**

As in point 2 above.

**Comment by zxtom** [comment] 2019-03-18 20:00
I can confirm this is still a problem in Xreader 2.0.2 (Mint 19.1 Cinnamon) - came across the same unexpected behaviour when trying to fill in a PDF form using Chinese (CJK) characters.

When the input field is in focus, the Unicode text is visible (screenshot 1 below), once not in focus it looks like only characters that belong to the ISO-8859-1 subset are displayed correctly in form elements (screenshot 2 below).

I'm attaching the sample PDF form file, screenshots, and a file with the sample text used to create the screenshots.

I'd be happy to help with testing and/or creating more sample files. Is there a chance for someone to look into this this please?

Screenshot 1: form field in focus
![screenshot_01-20190318](https://user-images.githubusercontent.com/24789853/54559220-70186300-49b7-11e9-87d9-1a0b70e0b408.png)

Screenshot 2: form field not in focus - note the Chinese characters are missing
![screenshot_02-20190318](https://user-images.githubusercontent.com/24789853/54559222-70186300-49b7-11e9-9b25-f659318e2004.png)

[test-xreader_pdf_form-sample_001.pdf](https://github.com/linuxmint/xreader/files/2980016/test-xreader_pdf_form-sample_001.pdf)

[sample_text.txt](https://github.com/linuxmint/xreader/files/2980024/sample_text.txt)

**Comment by icarter09** [comment] 2020-11-01 03:15
Xreader v2.6.4
Mint 20 64bit

Still an issue. Happens as exactly stated above, you can enter Cyrillic text in a given field, but only appears when that field is in focus.

**Comment by zxtom** [comment] 2020-11-01 10:21
Thanks for looking into this @icarter09 - will try my best to help with testing.

**Comment by icarter09** [comment] 2020-11-03 04:22
After some digging, this appears to be a long running issue within Poppler (https://gitlab.freedesktop.org/poppler/poppler/-/issues/463). I was able to track the issue to a point that went to the Poppler API, which then lead me to find the open bug ticket on the Poppler site. 
I'm going to close this ticket since the issue appears is with Poppler. I'll keep an eye on that issue as well to see if any progress occurs.

**Closed by icarter09** 2020-11-03 04:22 UTC
Labels: BUG, BUG REPRODUCED
