### ISSUE TITLE
Mouse wheel scroll always zoom out

### ISSUE THREAD

**Issue by yparitcher** [linuxmint/xreader#287] opened 2019-02-11 20:50 UTC
```
xreader 2.0.2
Mint 19.1
```

**Issue**
when zooming with the scroll wheel both up and down scroll zoom out 

**Expected behaviour**
scroll up should zoom in

**Comment by OndrejMalek** [comment] 2019-03-15 12:19
xreader 2.0.2
Mint 19.1

tested - works right, but does not work with imwheel

**Comment by yparitcher** [comment] 2019-03-17 19:16
thanks @OndrejMalek this issue is only with imwheel

**Comment by shahmajlani** [comment] 2019-04-05 09:12
I noticed this bug when running under xfce4 :mouse: and without having ```imwheel``` installed. It all works works well under cinnamon though.

If it helps,
```
xreader 2.02
xapps 1.4.5
xfce4~git
```

**Comment by shahmajlani** [comment] 2019-04-05 09:43
I just tested with xapps~git and incorrect scrolling behaviour seems to be fixed. :tada:

**Comment by jondo** [comment] 2019-09-10 10:58
I also see this, using Mint 19.1 Mate and Xreader 2.0.2. I never had imwheel installed.

**Comment by HenriDeh** [comment] 2019-11-22 14:06
Same here, never installed 'imwheel', I have this bug since always. Any fix ?

**Comment by nerozero** [comment] 2020-01-02 08:23
I have this bug too, Mint 19.1, Cinnamon, 64bit

**Comment by icarter09** [comment] 2020-03-28 16:21
xreader v2.4.3
Mint 19.3 Cinnamon 64bit

I do not have `imwheel` installed and used the `ctrl + scroll wheel` to zoom in/out. If that is the correct steps, then I'm not able to reproduce this issue. 

If anyone else is still having this issue, please let me know. Thanks.

**Comment by jondo** [comment] 2020-04-03 10:32
I still see this bug on Mint 19.3 Mate with xreader 2.4.4.

**Comment by icarter09** [comment] 2020-04-29 03:00
@jondo can you provide me the steps and keys you are using to reproduce this issue? Thanks.

**Comment by jondo** [comment] 2020-04-29 09:16
Same as you tried: I open a PDF file (e.g. http://africau.edu/images/default/sample.pdf) with Xreader, then use ctrl + scroll wheel to zoom. Both rotation corrections make the page smaller.

Additionally, I managed to reproduce the issue in the following way, which should also be available to you:
I boot a new VirtualBox machine directly from linuxmint-19.3-mate-64bit.iso.
Inside this fresh VM I download this sample.pdf and open it with Xreader. Then ctrl + scroll wheel behaves wrong again.

**Comment by icarter09** [comment] 2020-04-30 02:38
Odd. When I just now tried this out, couldn't reproduce the issue. Then after trying out the sample.pdf, I'm able to see both make the page smaller, but zooming in only does it on the 1st `ctrl + scroll`. After that it goes back to zooming in.

**Comment by jondo** [comment] 2020-05-02 14:13
So you are seeing at least _some_ strange effect? Could that be enough for debugging?

**Comment by icarter09** [comment] 2020-05-02 16:49
@jondo yes and yes. Appreciate the help and will start digging into this.

**Comment by icarter09** [comment] 2020-05-03 03:25
@jondo I was able to find the block of code that the issue stems from... https://github.com/linuxmint/xreader/blob/81b4ed68d93b6fc084dc3612d2521a0d31d43b00/libview/ev-view.c#L3466

I noticed that the issue will also occur every time I click off the given pdf and then attempt to zoom in. The first atttempt will not work, but the second one will. The issue is that the x and y deltas aren't set on the first attempt. Here's a link explaining the issue more in-depth(https://bugzilla.gnome.org/show_bug.cgi?id=675959).

I'm not noticing the issue with evince. I'm looking into how they implemented a fix for this and will be bringing that fix into xreader shortly.

**Comment by jondo** [comment] 2020-05-03 16:20
I have now tested with [this test.c](https://github.com/linuxmint/xreader/files/4570936/test.c.txt), which is the test case from [gtk+ bugzilla issue 704546 " First smooth scroll event has a delta_y of 0"](https://bugzilla.gnome.org/show_bug.cgi?id=704546).

With this program, scrolling three times 'up' (turning the mouse wheel away from me) and three times 'down' yields:
```
scroll event: direction = up, delta_y = 0,000000
scroll event: direction = up, delta_y = 0,000000
scroll event: direction = up, delta_y = 0,000000
scroll event: direction = down, delta_y = 0,000000
scroll event: direction = down, delta_y = 0,000000
scroll event: direction = down, delta_y = 0,000000
```

**Comment by jondo** [comment] 2020-05-03 16:53
Ah! I am sorry that I did not think of this before: My problematic machine is **remotely connected via RDP** (Remmina)!

For testing, I have now rebooted my local machine to a linuxmint-19.3-mate-64bit live session, and there I only see the same effect like @icarter09: After Xreader gets focus, the first zoom-out zooms in instead. This is also shown by test.c there (with the same wheel turns as before):
```
scroll event: direction = smooth, delta_y = 0.000000
scroll event: direction = smooth, delta_y = -1.000000
scroll event: direction = smooth, delta_y = -1.000000
scroll event: direction = smooth, delta_y = 1.000000
scroll event: direction = smooth, delta_y = 1.000000
scroll event: direction = smooth, delta_y = 1.000000
```

**Comment by jondo** [comment] 2020-05-03 17:42
I just wanted to suggest [this change](https://github.com/jondo/xreader/commit/0c52580123980cb79f68f0ad7fa8e4cc336e9da6) as a pull request, then I saw that the existing request https://github.com/linuxmint/xreader/pull/390, which (among lots of additional changes) contains similar code.

**Comment by icarter09** [comment] 2020-05-05 02:07
@jondo thanks for the input and looking into this. Yes the PR does contain the fix. I should have thought to look at that sooner, but completely forgot.

**Comment by jondo** [comment] 2020-05-05 22:21
The "only first zoom-in zooms out" behavior (which is not the main topic of this issue) is similar to issue #325.

**Comment by icarter09** [comment] 2020-05-12 02:23
@jondo the PR #390 was merged. Let me know if that resolves your issues. Thanks.

**Comment by jondo** [comment] 2020-05-13 18:50
Great! Seems as if version [2.6.0](https://github.com/linuxmint/xreader/commit/209cb27ec6b5348b08ee1a34f1c19caa0668c559) will be available soon for testing.

**Comment by icarter09** [comment] 2020-11-01 03:07
Xreader v2.6.4
Mint 20 64bit

This PR that contains the fix for this issue has been merged.

**Closed by icarter09** 2020-11-01 03:07 UTC
Labels: BUG
