### ISSUE TITLE
crazy scrolling

### ISSUE THREAD

**Issue by PKscrat** [linuxmint/xreader#291] opened 2019-03-02 19:29 UTC
```
 * Xreader version
xreader 2.0.2
 * Distribution
OS: LMDE 3 Cindy x86_64 
Kernel: 4.9.0-8-amd64 
DE: Cinnamon 4.0.9
```
**Issue**
Scrolling uncontrollable:
[See a demonstration video here.](https://youtu.be/WZMwam-h3XQ)

**Steps to reproduce**
Some documents are scrolling up and down when moving the mouse in that direction.
[You find a document here on which the problem occurs.](http://www.astraqua.eu/PDF/herbier_scan.pdf)

**Expected behaviour**
That fonction should be inactivated or eliminated, because it is superfluous with the auto-scrolling fonction (available by click on the right). 

**Other information**
[The problem also occurs here](https://github.com/linuxmint/xreader/issues/27), but it is independent fron the auto-scrolling fonction (not activated here).

**Comment by farvardin** [comment] 2019-04-15 15:18
It's the same bug as in https://github.com/linuxmint/xreader/issues/27 because people have this problem when they don't have the auto-scrolling function (which is not activated by default)
I got the same problem as well, with MATE

**Comment by Piiit** [comment] 2019-04-15 18:40
Maybe related to https://gitlab.gnome.org/GNOME/evince/issues/943...

**Comment by riksoft** [comment] 2019-04-26 14:48
This bug is a duplicate of the one I've already posted this bug 1 year ago with the precise steps to sistematically reproduce the problem on any document anytime:
https://github.com/linuxmint/xreader/issues/225

**Closed** 2019-04-29 15:03 UTC
