### ISSUE TITLE
Cannot start xreader after installation (Settings schema 'org.x.reader.toolbar' does not contain a key named 'show-zoom-action')

### ISSUE THREAD

**Issue by ch-sa** [linuxmint/xreader#352] opened 2019-12-18 13:51 UTC
```
 * Xreader version 2.0.2
 * Distribution - (Mint 19.1 Cinnamon)
 * Sys-Info: Linux Lenovo-E31 4.18.0-17-generic #18~18.04.1-Ubuntu SMP Fri Mar 15 15:27:12 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```

**Issue**
Hello,
I tried installing this github version of xreader according to the [README](README) and after I finished all the steps I could not start xreader anymore.

If I start xreader on the console I get the following error:
```
xreader
(xreader:23858): GLib-GIO-ERROR **: 14:41:17.297: Settings schema 'org.x.reader.toolbar' does not contain a key named 'show-zoom-action'
Trace/Breakpoint ausgelöst (Speicherabzug geschrieben)
```

**Steps to reproduce**
1) Follow the installation steps 1) to 5) from the README.
2) Run xreader

**Expected behaviour**
xreader should have startet with the updated version.

**Other information**
 * Before the installation there was the default xreader installed that comes with Linux Mint 19.1.
 * During compilation (`ninja -C debian/build
`) there were the following warnings/ errors:
<details><summary>Show Commando Output</summary>
<p>

```
[33/211] Compiling C++ object 'backend/pdf/pdfdocument@sha/ev-poppler.cc.o'.
../../backend/pdf/ev-poppler.cc: In function ‘GdkPixbuf* pdf_document_thumbnails_get_thumbnail(EvDocumentThumbnails*, EvRenderContext*, gboolean)’:
../../backend/pdf/ev-poppler.cc:1485:71: warning: ‘GdkPixbuf* ev_document_misc_get_thumbnail_frame(int, int, GdkPixbuf*)’ is deprecated [-Wdeprecated-declarations]
   border_pixbuf = ev_document_misc_get_thumbnail_frame (-1, -1, pixbuf);
                                                                       ^
In file included from ../../backend/pdf/ev-poppler.cc:41:0:
../../libdocument/ev-document-misc.h:42:12: note: declared here
 GdkPixbuf *ev_document_misc_get_thumbnail_frame  (int           width,
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
../../backend/pdf/ev-poppler.cc: In function ‘EvAnnotation* ev_annot_from_poppler_annot(PopplerAnnot*, EvPage*)’:
../../backend/pdf/ev-poppler.cc:2754:44: warning: ‘gboolean ev_annotation_set_color(EvAnnotation*, const GdkColor*)’ is deprecated: Use 'ev_annotaion_set_rgba' instead [-Wdeprecated-declarations]
   ev_annotation_set_color (ev_annot, &color);
                                            ^
In file included from ../../libdocument/ev-document-annotations.h:31:0,
                 from ../../backend/pdf/ev-poppler.cc:51:
../../libdocument/ev-annotation.h:142:22: note: declared here
 gboolean             ev_annotation_set_color                 (EvAnnotation           *annot,
                      ^~~~~~~~~~~~~~~~~~~~~~~
../../backend/pdf/ev-poppler.cc: In function ‘void pdf_document_annotations_add_annotation(EvDocumentAnnotations*, EvAnnotation*, EvRectangle*)’:
../../backend/pdf/ev-poppler.cc:3096:40: warning: ‘void ev_annotation_get_color(EvAnnotation*, GdkColor*)’ is deprecated: Use 'ev_annotaion_get_rgba' instead [-Wdeprecated-declarations]
  ev_annotation_get_color (annot, &color);
                                        ^
In file included from ../../libdocument/ev-document-annotations.h:31:0,
                 from ../../backend/pdf/ev-poppler.cc:51:
../../libdocument/ev-annotation.h:139:22: note: declared here
 void                 ev_annotation_get_color                 (EvAnnotation           *annot,
                      ^~~~~~~~~~~~~~~~~~~~~~~
../../backend/pdf/ev-poppler.cc: In function ‘void pdf_document_annotations_save_annotation(EvDocumentAnnotations*, EvAnnotation*, EvAnnotationsSaveMask)’:
../../backend/pdf/ev-poppler.cc:3230:44: warning: ‘void ev_annotation_get_color(EvAnnotation*, GdkColor*)’ is deprecated: Use 'ev_annotaion_get_rgba' instead [-Wdeprecated-declarations]
   ev_annotation_get_color (annot, &ev_color);
                                            ^
In file included from ../../libdocument/ev-document-annotations.h:31:0,
                 from ../../backend/pdf/ev-poppler.cc:51:
../../libdocument/ev-annotation.h:139:22: note: declared here
 void                 ev_annotation_get_color                 (EvAnnotation           *annot,
                      ^~~~~~~~~~~~~~~~~~~~~~~
```

</p>
</details>

**Comment by mtwebster** [comment] 2019-12-18 14:35
Hi,

Can you run this command:
```
sudo glib-compile-schemas /usr/share/glib-2.0/schemas
```

It looks as though the settings aren't being fully installed from the build.  Since you're in Linux Mint, you could simply git clone, then run '`dpkg-buildpackage`' and it would generate .deb packages for you - in this case the packaging system runs the above command on your behalf.

Using `ninja install` doesn't do this by default, there needs to be a script added to the build for this.  If that command fixes your issue, I'll fix the build.

**Comment by mtwebster** [comment] 2019-12-18 15:37
I was able to reproduce this here, and have pushed a fix so builds like this will install successfully.

**Closed** 2019-12-18 15:37 UTC

**Comment by ch-sa** [comment] 2019-12-19 10:33
Thank you @mtwebster.

The installation according to the README now works smoothly.
I also tried  building a *.deb-package with `dpkg-buildpackage` before, but that created a ton of packages that mostly could not be installed due to requirements. But this could be specific to my system.

Anyway xreader now works well in version 2.4.3 and supports text annotation. :raised_hands:
