### ISSUE TITLE
Misrendered object border

### ISSUE THREAD

**Issue by ghost** [linuxmint/xreader#249] opened 2018-09-20 00:20 UTC
```
 * Xreader version (xreader --version) 1.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 19 Cinnamon
```

**Issue**
I created a document in Word, on Windows, and converted it to PDF. The PDF displays correctly: in Sumatra PDF on Windows; on Ocular on Mint; on Adobe Reader, under Wine, on Mint; but not in Xreader. The problem is a single box around one element on one page - but this problem undermines my confidence in using xreader for presentations.

Screenshot of the page as it is meant to look:

![image](https://user-images.githubusercontent.com/9998846/45788508-dc1d4700-bc72-11e8-949d-43fec6d0b410.png)

Screenshot of the page in xreader - note the extraneous rectangular grey border around one of the page elements:

![image](https://user-images.githubusercontent.com/9998846/45788538-14bd2080-bc73-11e8-8edc-35b04c05af29.png)

**Steps to reproduce**

Uncertain.

**Expected behaviour**

The other PDF readers render the file correctly, i.e. as the PDF looked in Word before being converted to PDF.

**Other information**

I can supply the PDF (though I'd rather not do so on the open web).

**Comment by icarter09** [comment] 2019-12-18 04:05
Closing due to submitter of the issue is no longer present on github.

**Closed by icarter09** 2019-12-18 04:05 UTC
Labels: BUG
