### ISSUE TITLE
Crash upon highlight and saving / replacing

### ISSUE THREAD

**Issue by binyominzeev** [linuxmint/xreader#613] opened 2023-07-30 10:46 UTC
```
 * Xreader version: 3.8l.2
 * Distribution - Mint 21.2
```

**Issue**

Xreader crashes upon saving and replacing existing file.

**Steps to reproduce**

1. Open the file.
2. Highlight / annotate something.
3. Save it to the same file, by choosing replace
4. Xreader exits, with no error message in console, and file remains unchanged.

**Expected behaviour**

Save the file with the changes and leave xreader open.

**Other information**

The issue occurred with the following PDF file:

https://download.hebrewbooks.org/downloadhandler.ashx?req=42852

**Comment by edgarogh** [comment] 2023-07-31 14:57
Same issue with completely different PDFs. No error in console (apart from the usual GTK warnings).

**Comment by mtwebster** [comment] 2023-07-31 15:09
This seems to be a duplicate of #609, fixed, just needs a new version.

**Closed by mtwebster** 2023-07-31 15:09 UTC

**Comment by binyominzeev** [comment] 2023-08-20 05:07
Sorry, what is the most recent version and how can I upgrade to it? Will it be available through package?

Currently I see 3.8.2 is the most recent and this is what I have.

**Comment by edgarogh** [comment] 2023-08-20 08:54
@binyominzeev Packages in Mint take time to update, you'll have to be patient, and make sure you're on the latest version of Mint in the first place

**Comment by scytho** [comment] 2023-10-24 19:50
Same here. In Mint, Xreader is on 3.8.2, which is the newest version I can see here on Github.

**Comment by edgarogh** [comment] 2023-10-24 20:02
> Same here. In Mint, Xreader is on 3.8.2, which is the newest version I can see here on Github.

That's probably because a new release wasn't published yet. But if you compile straight from GitHub, the issue is fixed as expected.

**Comment by scytho** [comment] 2023-11-21 15:34
Is [this](https://github.com/linuxmint/xreader/releases/tag/master.mint21) a new release? Who has to add it to the repos for Mint?
