### ISSUE TITLE
Xreader consumes too much RAM!!!

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/xreader#37] opened 2016-08-30 19:31 UTC
![screenshot at 2016-08-30 23-17-39](https://cloud.githubusercontent.com/assets/13224708/18103564/407b108e-6f08-11e6-9a42-e1a3372bc88c.png)

Isn't it a bit much for a simple PDF reader?

Here is the file to reproduce it.

[Rihter_-_CLR_via_C%23._Programmirovanie_na_platforme_Microsoft_.NET_Framework_2.0_na_yazyke_C%23.pdf](https://github.com/linuxmint/xreader/files/445763/Rihter_-_CLR_via_C.23._Programmirovanie_na_platforme_Microsoft_.NET_Framework_2.0_na_yazyke_C.23.pdf)

This problem doesn't occur immediately, the memory usage gradually increases during page scrolling.

**Comment by Piiit** [comment] 2016-11-05 13:39
@surenenfiajyan Hi, with the newest build I cannot reproduce this issue. I have 53MB after some minutes of scrolling. It could be that it was a memory leak already solved with the last commits. 

Could you test if this still happens with xreader 1.2.0? See https://github.com/linuxmint/xreader/issues/33#issuecomment-247851424 and https://github.com/linuxmint/xreader/issues/62#issuecomment-258081056 for further details.

**Comment by Piiit** [comment] 2017-03-28 10:13
@surenenfiajyan Any news on this?

**Comment by Piiit** [comment] 2017-04-28 08:08
@JosephMcc Close if no response?

**Comment by JosephMcc** [comment] 2017-04-28 08:58
I'll go ahead and close this. It can always be reopened if there is a response.

**Closed by JosephMcc** 2017-04-28 08:58 UTC

**Comment by dugganjl** [comment] 2023-04-26 04:05
I am experiencing the same. I have had 11 PDFs open for several days (having scrolled through each several times), with each PDF between 50 - 500 kB in size, and now their memory usage per file is between 255 MB - 1 GB. 

LMDE 5
Xreader 3.4.5
