### ISSUE TITLE
Highlighted text becomes mirrored

### ISSUE THREAD

**Issue by terr72** [linuxmint/xreader#381] opened 2020-04-22 06:48 UTC
```
 * Xreader 2.4.4
 * Distribution - Mint 19.3 64bit
```

**Issue**

When marking text, the text is mirrored.

**Steps to reproduce**

1. Download this PDF from here: https://www.siemens-home.bsh-group.com/de/getAllImagesPDF?vibki=WM14VM90%2F01
2. Mark any text.
3. Marked text is mirrored - see also the attached screenshot.
![font_inverse_screenshot](https://user-images.githubusercontent.com/23163919/79949448-e10d3280-8475-11ea-9a8f-148b9933b7c2.png)

**Expected behaviour**

Text shouldn'be mirrored.

**Comment by icarter09** [comment] 2020-04-25 02:03
Xreader v2.4.4
Mint 19.3 64bit

Was able to reproduce this issue with the PDF in the link. Tried this on several other PDFs, but wasn't able to reproduce the issue with them.

**Comment by terr72** [comment] 2020-04-25 06:20
This seems to have been already brought up in the past in bug https://github.com/linuxmint/xreader/issues/341

**Comment by icarter09** [comment] 2020-04-25 17:57
Debugged the issue in Xreader and was able to see that the issue resides with Poppler. Tested this issue out on Atril and Evince. Both had the same issue, which helped to verify the issue being with Poppler. Also went over the Poppler issue tracker and found the same issue (https://gitlab.freedesktop.org/poppler/poppler/-/issues/473). 

I'm going to close this ticket since it's a Poppler issue and not an Xreader issue. Will continue to look into this issue, but instead from the Poppler gitlab repo and address it from there.

**Closed** 2020-04-25 17:57 UTC
Labels: BUG REPRODUCED
