### ISSUE TITLE
why does this scroll around when application not even current focus, makes it unusable ?

### ISSUE THREAD

**Issue by jonshouse1** [linuxmint/xreader#268] opened 2018-12-13 00:49 UTC
```
 * Xreader version (xreader --version)
1.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...)
XFCE desktop

**Issue**
Even when not the current focus the pdf viewer scrolls up and down as the mouse is moved. Reading a pdf at the same time as doing ANYTHING else at all is impossible. Horrible !


**Steps to reproduce**
Mint 19 XFCE desktop, just try and use it.


**Expected behaviour**
KEEP STILL - STOP SCROLLING AROUND !   I have a 4k 40inch monitor, I want to able to have more than one window active at a time..........


**Other information**

**Comment by Piiit** [comment] 2019-04-29 15:07
@jonshouse1 Duplicate of #27, #225 and #291. Now fixed in master... please close

**Closed** 2019-05-05 18:13 UTC
