### ISSUE TITLE
Feature request: option to disable auto scroll

### ISSUE THREAD

**Issue by M1chael** [linuxmint/xreader#27] opened 2016-07-19 16:02 UTC
I am not sure, it is XReader feature or maybe Cinnamon: when I move mouse to top or down of screen auto scrolling starts. It is very annoying for me. Can you add a disable option for it?
**UPD**: reopening document disable auto scroll.

**Comment by Cos-mo** [comment] 2016-08-29 10:47
There is an option for auto-scroll in the context menu of the page; it is off by default.

**Comment by Vahan86** [comment] 2016-10-28 07:31
The auto-scroll option is disabled by default in Xreader.

@JosephMcc, can we close this issue?

**Comment by linamist** [comment] 2017-05-17 18:57
The same thing happens to me :-(

**Comment by jessewriter** [comment] 2017-08-11 18:11
This was super annoying as I moved my mouse up the scroll scrolled even though I was not dragging nor was I using the scroll wheel.  I did seem to find a workaround by right clicking on the page and clicking on autoscroll a few times this seemed to somehow release my mouse movements from scrolling the page.

**Comment by jackchouchani** [comment] 2017-12-19 23:07
This issue is still super annoying, and I can't seem to find a workaround.

**Comment by riksoft** [comment] 2018-04-17 18:00
Same here. Xreader is the only app on Mint 18.3 that scroll by itself when the mouse is on top or bottom of the screen, even if xreader has not the focus and even if my mouse is on another monitor. Even in this moment: I'm writing in firefox on monitor 1, but if I move the mouse on top/bottom of this monitor, on monitor 2 xreader scroll up/down.

This is massively annoying and irritating because when I open, e.g. an XML doc in Xreader on monitor 2 and develop on Netbeans on monitor 1, quite often Xreader move aroud and I have to waste time to get back at the proper point... so that most of the time I end up using the js pdf reader of Firefox.

**Comment by riksoft** [comment] 2018-04-17 18:12
By the way I have no idea WHEN/WHY it starts to behave such way. Closing the document and reopening solve the problem for a while, then something happens and Xreader starts to behave that way again.

**Comment by gitman0** [comment] 2018-06-08 15:37
xreader 1.6 on Fedora 27 Cinnamon. If I place my mouse cursor at the top or the bottom of the window, it automatically scrolls. It scrolls even when the mouse is hovering over the panels that I have at the top and bottom. This is not the same as the auto-scroll function available in the context menu, which visibly changes the mouse cursor to the double arrow when activated.

**Comment by farvardin** [comment] 2019-04-15 15:08
same here, except it's certainly not a problem with Cinnamon, I'm using Linux Mint 19 with the Mate desktop.
It looks a bit like the auto-scroll function, but it's not (no double arrow). Sometimes when activating and unactivating the auto-scroll it does stop the bug.

**Comment by riksoft** [comment] 2019-04-15 18:17
I found the cause 1 year ago, still unissigned, and is explained here:
https://github.com/linuxmint/xreader/issues/225#issuecomment-434917530

**Closed** 2019-04-29 15:03 UTC
