### ISSUE TITLE
Text selection regression for Hi-DPI displays

### ISSUE THREAD

**Issue by mpetroff** [linuxmint/xreader#162] opened 2017-08-28 22:30 UTC
```
 * Xreader version: master / 1.4.4
 * Distribution - (Mint 18.2)
```

**Issue**

The changes to `libview/ev-pixbuf-cache.c` in e76a18dfedfd769268bfb98fda9d6c3596373620 break text selection rendering on hi-DPI displays, with the display scaling factor not being applied to highlight rendering.

![bug](https://user-images.githubusercontent.com/1450212/29796243-1361ee72-8c1e-11e7-95db-36ba3ca0b495.png)

This only happens when text is selected with the mouse; the selection is rendered correctly when using `ctrl-a` and when it is redrawn after the page is scrolled. Since it looks correct after a redraw, I assume the initial drawing was always incorrect but that the redraw loop that e76a18dfedfd769268bfb98fda9d6c3596373620 fixes was hiding the problem.

**Comment by realskorpion** [comment] 2018-01-21 03:04
Hi
Same issue here.

**Comment by ltden** [comment] 2018-02-25 20:49
I have the same issue on 4K display.

**Comment by Desposyni** [comment] 2018-10-19 18:42
Same issue. Anything I can do to contribute to a fix?

**Comment by ltden** [comment] 2019-02-25 08:37
Same issue.

**Comment by Piiit** [comment] 2019-05-04 07:46
Duplicate of #95. Thx for reporting...

**Closed** 2019-05-04 07:47 UTC

**Comment by mpetroff** [comment] 2019-05-04 15:37
It's not really a duplicate, as the user who opened #95 was not using a hi-DPI display, and the change that caused this problem was committed after that issue was opened. After this issue was opened, people began erroneously commenting on the previous, mostly unrelated, issue instead of this issue. 

Regardless, it's great that it's getting fixed now; I had made some attempts to fix this but never got anywhere with it.

**Comment by Piiit** [comment] 2019-05-05 18:12
You are right. However, the other issue and related comments describe the whole problem in a good enough depth to be tackled. It contains hidpi descriptions as well, so we do not loose information by closing this.
