### ISSUE TITLE
selecting text does not work.

### ISSUE THREAD

**Issue by Laurencio** [linuxmint/xreader#95] opened 2017-02-15 00:25 UTC
Can't select text whith the mouse in pdf documents, specially when the window is maximized. when not, it works better. Crtl-A works for me.
I'm using Linux Mint 18.1 XFCE.
This feature in evince works well with the same documents.

**Comment by Piiit** [comment] 2017-04-19 11:42
@Laurencio Hi, could you please upload a test pdf file that works in evince, but not in xreader.

**Comment by Laurencio** [comment] 2017-06-11 20:44
Sorry i come so late.
Here are 2 examples. But it happens with almost all pdf files. Seems i am the only one that has this problems. But i have it on two different machines.

[previsualizacion.pdf](https://github.com/linuxmint/xreader/files/1066756/previsualizacion.pdf)

[ejemplo2.pdf](https://github.com/linuxmint/xreader/files/1066755/ejemplo2.pdf)

**Comment by JosephMcc** [comment] 2017-06-11 21:01
I tried both of your test files under XReader 1.4. Could select text with no issues. When you get the chance try retesting under 1.4 and see if it's improved.

**Comment by Laurencio** [comment] 2017-06-19 23:21
Strange.
Tried it again on a live Linux Mint 18.2 XFCE Beta, wich brings XReader 1.4 and experience the same issues. Selecting text does not work whith mouse "click & drag" over text on pdf documents

**Comment by Piiit** [comment] 2017-09-14 08:07
@Laurencio Do you use HiDPI resolution?

**Comment by sevhau** [comment] 2017-09-19 13:11
I have a similar issue with HiDPI and 2 screens attached with cinnamon.
Its one of 2 cases:
1.The selected text only gets visible when i right click after selection. During the click&drag nothing is visible. 
2. The selection is rendered with highlighting in a bigger font somewhere else on page when click&drag.

Double-click selection(word) has the same issue as 1. Selecting a line does work.

**Comment by proximous** [comment] 2017-11-09 17:02
Similar issue with HiDPI.  I can successfully select text, however the text does not highlight as I select it. If I scroll the window, the text appears highlighted.  If the text I select is near the top of the screen, I will see text highlighting lower on the screen.  I can provide a screen shot of that if it helps.

It seems the selection is happening, just not being drawn in the correct location.

**Comment by Laurencio** [comment] 2017-12-22 02:29
@Piiit Sorry i haven't been here for a while.
I don't use HiDPI.

**Comment by Piiit** [comment] 2017-12-22 08:04
@Laurencio Maybe it is a theming issue. Could you pls try other themes? Or tell which one you're currently using. Thx

**Comment by Laurencio** [comment] 2018-01-19 19:05
Hello.
I'm on Linuxmint 18.3 xfce now. xreader 1.6.2. Selecting text on pdf is fine now. With all themes i had tried.
Thanks.

**Comment by realskorpion** [comment] 2018-01-21 03:01
Hi.

Same issue here with HiDPI.
I'm using Linux mint 18.3
Switching to evince until the problem is fixed.

Thanks.

**Comment by a2hostingwebdev** [comment] 2018-02-19 17:34
Same issue here with HiDPI.
Also Linux mint 18.3 cinnamon.
I have found that the text appears to actually get selected with click & drag, but the screen does not show it.  If I click or alt-tab to another window I can see the selection area flash up as it switches.  Then when I come back, text is selected and I can copy it etc.

**Comment by CurtC2** [comment] 2018-02-19 17:38
Same issue here with HiDPI in a PDF.
Also Linux mint 18.3 cinnamon.
I have found that the text appears to actually get selected with click & drag, but the screen does not show it. If I click or alt-tab to another window I can see the selection area flash up as it switches. Then when I come back, text is selected and I can copy it etc.

**Comment by ltden** [comment] 2018-02-25 20:53
Same issue, Mint 18.3, HiDPI

**Comment by Etamuk** [comment] 2018-10-03 21:27
Exactly this problem still exists on my system too. 
Cinnamon 3.8.8 on Manjaro Linux. 4K-HiDPI-Screen.

**Comment by kybos** [comment] 2018-12-15 09:46
Same problem here.
Mint 19 Cinnamon, HiDPI.
XReader 1.8.5

**Comment by gm10** [comment] 2018-12-15 13:59
Confirming for Mint 19.1 MATE, xreader 2.0.2+tessa, only with HiDPI setting.

**Comment by Piiit** [comment] 2019-04-30 15:47
I got started with this bug fix, see progress at https://github.com/linuxmint/xreader/pull/302

**Comment by Piiit** [comment] 2019-05-02 07:23
@Laurencio @JosephMcc @gm10 @sevhau @proximous @kybos @Etamuk @CurtC2 @realskorpion 
Fixed in my PR #302... please test, if possible with different file types.

**Closed** 2019-06-12 15:00 UTC
