### ISSUE TITLE
Selection scaling on a 4K screens

### ISSUE THREAD

**Issue by etzvetanov** [linuxmint/xreader#303] opened 2019-05-03 18:25 UTC
```
 * Xreader version (xreader --version) 
1.8.5
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) 
Mint 19 Tara
```

**Issue**
The format of my screen is UHD (4K display 3840x2160 pixels (16:9)) format.
Displaying the document works well. Scrolling too. When a selection attempt is made,  the selection strip is displaced below and only visible partially if the line selected is above the half of the window. (See attached). It is also twice the size in both dimensions.

Further more the line shows selected if the viewer loses focus and the focus is returned to the viewer.

**Steps to reproduce**
Use a Lenovo gaming laptop or something utilizing UHD resolution.
Load a document and try to select text line in it.

**Expected behaviour**
Selection shows over the line of selection (normal editor selection operation behavior)

**Other information**
![Screenshot from 2019-05-03 14-22-25](https://user-images.githubusercontent.com/48278665/57157646-4ffa0300-6daf-11e9-8720-0668f4b44d80.png)

**Comment by Piiit** [comment] 2019-05-03 20:07
Duplicate of #95

**Closed** 2019-05-04 06:51 UTC
