### ISSUE TITLE
CPU usage after searching

### ISSUE THREAD

**Issue by marozols** [linuxmint/xreader#157] opened 2017-08-10 12:17 UTC
```
 * Xreader version 1.2.2
 * Distribution: Linux Mint 18.1 Cinnamon 64-bit
```

**Issue**

If I open any PDF document in xreader and then search in it, the CPU usage by xreader reaches about 8% and it does not decrease even once the whole document has been processed.

**Steps to reproduce**

Search any phrase in any PDF document. Just leave it running for a while and don't press anything (let it process the whole document). Then check the xreader CPU usage. I would expect it to go down to zero once the whole document has been processed, but it keeps hovering at around 8% for no good reason. This is annoying because it makes my laptop start to heat up and turn on the fan.

**Comment by Piiit** [comment] 2017-08-10 15:22
Hi @marozols, 
thx for reporting this bug. However, it is a duplicate of #70, and already fixed since version 1.4.3... 
Please close.

**Closed** 2017-08-11 09:49 UTC
