### ISSUE TITLE
Case sensitive search doesn't work

### ISSUE THREAD

**Issue by surenenfiajyan** [linuxmint/xreader#101] opened 2017-03-16 19:51 UTC
This problem seems to be fixed in Atril, but hasn't been yet backported.

**Comment by Piiit** [comment] 2017-03-17 07:58
Hi, a pull request to fix this issue is pending... See #73. 
You can close this issue therefore.

**Comment by Piiit** [comment] 2017-03-17 07:58
Duplicate of #47

**Closed** 2017-03-17 08:09 UTC
