### ISSUE TITLE
Sometimes <space> advances to the next slide and sometimes it does not

### ISSUE THREAD

**Issue by ghost** [linuxmint/xreader#170] opened 2017-09-18 01:23 UTC
```
 * Xreader version (xreader --version): 1.4.4
 * Distribution - (Mint 17.2, Arch, Fedora 25, etc...) Mint 17.2 x64 Cinnamon
```

**Issue**

Sometimes <space> advances to the next slide and sometimes it does not. I find that (1) the page-down key always works, (2) <space> always works once one had been through the whole file once.

**Steps to reproduce**

Open a multi-page file. Try to advance through it just by pressing space. If it works, try another file (for the problem may not beset all files; if necessary I could, privately, supply a file).

**Expected behaviour**

<Space> should behave consistently.

**Other information**

There are no forms in the PDFs I have had the problem with. All those PDFs were created by Word 2013.

**Comment by icarter09** [comment] 2019-12-18 04:02
Closing due to the submitter of the issue is no longer present on github.

**Closed by icarter09** 2019-12-18 04:02 UTC
Labels: BUG
