### ISSUE TITLE
Crash on Reload

### ISSUE THREAD

**Issue by reaganf2** [linuxmint/xreader#44] opened 2016-09-12 20:57 UTC
Xreader crashes with a segmentation fault when I hit Reload (Ctrl+R) while viewing a PDF. Running Xreader on a fresh install of Linux Mint 18.

**Comment by Piiit** [comment] 2016-09-13 09:54
@reaganf2  Hi, I cannot reproduce this issue. Does it happen with every PDF or just some. If so, could you upload a PDF file that causes this SEGFAULT.

**Comment by wylebe** [comment] 2016-09-13 19:51
I am having the same issue, and it's very random. It usually happens to me when a PDF is already open in Xreader and an updated version is exported from LibreOffice.

**Comment by reaganf2** [comment] 2016-09-13 22:37
It happens most of the time, and seems to not be dependent on the individual PDF. At times, the same PDF has and has not segfaulted upon reload.

**Comment by Piiit** [comment] 2016-09-14 06:50
@reaganf2  @wylebe I think this is a duplicate of #25 and #33 which has already been fixed with patch #28.
Could you please check if this patch also fixes your issue?

**Comment by reaganf2** [comment] 2016-09-14 07:10
I'm using the current version from the LM18 repo: v1.0.8.
Not quite sure if this contains the patch.

**Comment by reaganf2** [comment] 2016-09-19 01:43
I can confirm that building the latest version fixed this problem.

**Comment by Piiit** [comment] 2016-09-19 05:36
Perfect. Please close the issue... 

Thx for reporting

**Closed** 2016-09-19 05:42 UTC
