### ISSUE TITLE
Memory consumption

### ISSUE THREAD

**Issue by GAN-pie** [linuxmint/xreader#594] opened 2023-04-11 08:58 UTC
```
 Xreader 3.0.2
 Linux Mint 20.2
```

Memory consumption of xreader is skyrocketing when using annotation tool

When adding highlight annotations to the document, xreader make use of more and more memory until the system kills xreader.

**Expected behaviour**

**Other information**

**Comment by okaestne** [comment] 2023-04-20 20:26
Likely a duplicate of #548

**Closed** 2023-04-22 16:03 UTC
