### ISSUE TITLE
Selected text does not appear correctly on 4K screens.

### ISSUE THREAD

**Issue by faliagas** [linuxmint/xreader#229] opened 2018-05-21 20:32 UTC
```
 * Xreader version 1.6.2
 * Distribution - Mint 18.3
```

**Issue**
On 4k displays, the selected text does not appear correctly (it is not highlighted). It appears correctly after a click on the titlebar. The problem does not appear on displays with lower resolution.

**Steps to reproduce**
Select text with the mouse (display must be 4k).

**Expected behaviour**
The selected text should have a colored background.

**Other information**

**Comment by mpetroff** [comment] 2018-07-06 18:53
This is a duplicate of #162.

**Comment by JosephMcc** [comment] 2018-07-06 19:45
Thanks for pointing that out.

**Closed by JosephMcc** 2018-07-06 19:45 UTC
