### ISSUE TITLE
not saving changes to a dropdown in an embedded form

### ISSUE THREAD

**Issue by xndrme** [linuxmint/xreader#12] opened 2016-06-15 07:17 UTC
After changing a dropdown selection in an embedded form (pdf) and saving the document, the change is not reflected: if the document is opened again the dropdown choice is unchanged.
This issue can be tested with [this](https://www.ed-sfa-unice.fr/sites/default/files/Inscription_SFA_2016_1.pdf) document.
Note: with evince the changes are saved correctly.

**Comment by Piiit** [comment] 2016-06-15 08:52
Your website is considered unsafe! Could you provide another (safe) pdf?

**Comment by xndrme** [comment] 2016-06-15 09:01
It's just the website of the University of Nice, I think they have a problem with the ssl certificate.
Here a Dropbox link: https://www.dropbox.com/s/1uylkg13mkg7dii/Inscription_SFA_2016_1.pdf?dl=0

**Comment by Piiit** [comment] 2016-06-17 08:31
OK, I tested it. 

Some dropdowns (ex., Qualité) only update if you change value and then move to another field. Saving the document then gives the right result. In contrast, if you do not leave the dropdown (that is, click on it, choose + click a new value = dropdown list closes, but stay inside the form) the old value is stored in file instead. I think this is not intuitive. 

Other dropdowns (like Laboratoire) can not be changed anymore after first change + save. Do you experience the same?

**Comment by Piiit** [comment] 2016-06-17 09:01
I think it is related to poppler, which does not support XFA forms as I know...
Please see: https://bugs.freedesktop.org/show_bug.cgi?id=18935

**Comment by xndrme** [comment] 2016-06-17 10:01
Well, yes, more or less is the same for me. The issue you described with "Laboratoire" also happens with "AUTORISATION D'INSCRIPTION ..." (the first dropdown at the top). "Qualité" and "Financement" behave the same, I think is because on these cases we are allowed to write text, is more like a combo-box, as opposed to pure dropdown choice on the first two ("Laboratoire" and  "AUTORISATION..").

I was wondering, if it works on Evince, is it possible to fix it here also? I'm not an expert but as far as I know Evince uses poppler too.

**Comment by xndrme** [comment] 2016-06-17 10:03
Just rechecked and in evince everything works like a charm. I don't know if this is relevant but I'm using Linux Mint 18 Cinnamon edition, and this should be fixed if we are going to replace evince with xreader as default document viewer.

**Comment by Piiit** [comment] 2016-06-17 10:17
@xndrme You are right, it works on Mint 17.3 with Evince 3.10.3 too. This is a pretty old version of evince, I am wondering why it has not been merged into atril (and xreader) yet? However, I am not familiar with the development of these projects. Just started a few days ago to have a look into code base :-)

**Comment by Piiit** [comment] 2016-06-19 09:01
Hi,
maybe I found and fixed this issue, could you please checkout and test the following branch:
https://github.com/Piiit/xreader/tree/issue12

I think it is a regression from commit 
https://github.com/linuxmint/xreader/commit/f8aec907364307470991b0b0d1b7b883c7397c57

I am not sure if my fix is the right way to go, since GTK_IS_COMBO_BOX is deprecated...
What do you think?

**Comment by Piiit** [comment] 2016-06-26 07:51
@clefebvre 
@xndrme 
I uploaded the test file to github (see #17), I think it is safe to close this issue now!

**Closed** 2016-06-26 11:30 UTC

**Comment by xndrme** [comment] 2016-06-26 11:34
Thanks Piit, great work! I've checked with the last official update of xreader (which includes your changes) and everything is OK.
