### ISSUE TITLE
Inverted colors setting not stored as default

### ISSUE THREAD

**Issue by Balteus** [linuxmint/xreader#83] opened 2016-11-17 08:25 UTC
"Store current settings as default" does not save the setting inverted colors activated. I have a dark theme and normally I want that all PDFs will be displayed as inverted (as default).

**Comment by Piiit** [comment] 2016-11-17 15:16
@Balteus Duplicate of #38.

**Comment by Vahan86** [comment] 2016-11-20 18:42
@JosephMcc, can we close this issue as it is a duplicate of issue #38.

**Closed** 2016-11-30 19:21 UTC
